;; Generated by :claw at 2026-02-06T21:17:51.613824Z
(asdf:defsystem #:claw-wx-bindings
  :description "Bindings generated by claw-wx"
  :author "CLAW"
  :license "Public domain"
  :defsystem-depends-on (:trivial-features)
  :depends-on (:uiop :cffi :iffi)
  :components
  ((:file "bindings/x86_64-pc-linux-gnu" :if-feature (:and :x86-64 :linux))))
#-(:or (:and :x86-64 :linux))
(warn "Current platform unrecognized or unsupported by claw-wx-bindings system")